// Generated by LiveScript 1.6.0
(function(){
  var btc, eth, eth_legacy, symblox, symbloxV2, xzo_usdv, ltc, usdt, xzo_native, xzo_erc20, xzo_evm, xzo_evm_legacy, bnb, xzo_busd, busd, huobi, xzo_huobi, xzo_usdt, xzo_eth, usdt_erc20, usdt_erc20_legacy, usdc, xzo_usdc, bsc_xzo, ref$, objToPairs, pairsToObj, filter, onlyCoins, extendCoins, toString$ = {}.toString;
  btc = require('./plugins/btc-coin');
  eth = require('./plugins/eth-coin');
  eth_legacy = require('./plugins/eth-legacy-coin');
  symblox = require('./plugins/symblox');
  symbloxV2 = require('./plugins/symblox-v2');
  ltc = require('./plugins/ltc-coin');
  usdt = require('./plugins/usdt-coin');
  xzo_native = require('./plugins/sol-coin');
  xzo_erc20 = require('./plugins/xzo_erc20-coin');
  xzo_evm = require('./plugins/xzo-coin');
  xzo_evm_legacy = require('./plugins/xzo-evm-legacy-coin');
  bnb = require('./plugins/bnb-coin');
  xzo_busd = require('./plugins/xzo_busd-coin');
  busd = require('./plugins/busd-coin');
  huobi = require('./plugins/huobi-coin');
  xzo_huobi = require('./plugins/xzo-huobi-coin');
  xzo_usdt = require('./plugins/xzo-usdt-coin');
  xzo_eth = require('./plugins/xzo-eth-coin');
  usdt_erc20 = require('./plugins/usdt_erc20.json');
  usdt_erc20_legacy = require('./plugins/usdt_erc20_legacy-coin.json');
  usdc = require('./plugins/usdc-coin');
  xzo_usdc = require('./plugins/xzo_usdc-coin');
  bsc_xzo = require('./plugins/bsc-xzo-coin');
  xzo_usdv = require('./plugins/xzo_usdv-coin.js');
  ref$ = require('prelude-ls'), objToPairs = ref$.objToPairs, pairsToObj = ref$.pairsToObj, filter = ref$.filter;
  onlyCoins = function(plugins){
    return pairsToObj(
    filter(function(it){
      var ref$;
      return ((ref$ = it[1]) != null ? ref$.type : void 8) === 'coin';
    })(
    objToPairs(
    plugins)));
  };
  extendCoins = function(coins, config){
    if (toString$.call(config.plugins).slice(8, -1) !== 'Object') {
      return;
    }
    return importAll$(coins, onlyCoins(config.plugins));
  };
  module.exports = function(config, cb){
    var def;
    def = {
      btc: btc,
      eth: eth,
      ltc: ltc,
      usdt: usdt,
      xzo_erc20: xzo_erc20,
      xzo_eth: xzo_eth,
      xzo_native: xzo_native,
      xzo_evm: xzo_evm,
      symblox: symblox,
      symbloxV2: symbloxV2,
      bnb: bnb,
      xzo_busd: xzo_busd,
      busd: busd,
      huobi: huobi,
      xzo_huobi: xzo_huobi,
      xzo_usdt: xzo_usdt,
      eth_legacy: eth_legacy,
      usdt_erc20: usdt_erc20,
      usdt_erc20_legacy: usdt_erc20_legacy,
      usdc: usdc,
      xzo_usdc: xzo_usdc,
      bsc_xzo: bsc_xzo,
      xzo_evm_legacy: xzo_evm_legacy,
      xzo_usdv: xzo_usdv
    };
    extendCoins(def, config);
    return cb(null, def);
  };
  function importAll$(obj, src){
    for (var key in src) obj[key] = src[key];
    return obj;
  }
}).call(this);
